/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/profissional/disponibilidade": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Lista a disponibilidade semanal da profissional autenticada
         * @description PF1. Retorna todas as faixas cadastradas, inclusive as inativas.
         */
        get: operations["listarDisponibilidade"];
        /**
         * Substitui a disponibilidade semanal completa
         * @description PF1. Operação de substituição total, executada em transação: as faixas enviadas
         *     passam a ser as únicas existentes. Enviar `faixas: []` limpa a agenda.
         *
         *     Não cancela sessões já marcadas fora das novas faixas — sessões existentes são
         *     preservadas e devolvidas em `sessoesForaDaNovaAgenda` para que a profissional
         *     decida o que fazer.
         */
        put: operations["definirDisponibilidade"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/profissional/bloqueios": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Lista os bloqueios de agenda
         * @description PF2. Por padrão retorna apenas bloqueios que ainda não terminaram.
         */
        get: operations["listarBloqueios"];
        put?: never;
        /**
         * Cria um bloqueio de agenda
         * @description PF2. O bloqueio remove slots futuros do período, mas **não cancela** sessões
         *     já marcadas. As sessões existentes no período são devolvidas em
         *     `sessoesAfetadas` para que a profissional as cancele manualmente, uma a uma.
         */
        post: operations["criarBloqueio"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/profissional/bloqueios/{bloqueioId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Remove um bloqueio de agenda
         * @description PF2. Os slots do período voltam a ser gerados imediatamente.
         */
        delete: operations["removerBloqueio"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/profissional/valores": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Lista os valores por tipo de sessão
         * @description PF3. Retorna os cinco tipos de sessão. Tipos sem valor definido vêm com
         *     `valor: null` e significam que a profissional **não oferece** aquele tipo.
         */
        get: operations["listarValores"];
        /**
         * Define os valores por tipo de sessão
         * @description PF3. Substituição total. Enviar `valor: null` para um tipo remove a oferta
         *     daquele tipo. Não afeta o `valorPraticado` de sessões já marcadas, que é um
         *     snapshot tirado no momento do agendamento.
         */
        put: operations["definirValores"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/profissional/agenda": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Lista as sessões da profissional autenticada
         * @description PF5. Inclui sessões individuais marcadas e sessões de grupo criadas.
         *
         *     **Janela default sugerida ao abrir a tela:** `de = hoje − 14 dias`,
         *     `ate = hoje + 30 dias`. As sessões que aguardam registro estão no passado; uma
         *     janela que começa hoje esconderia as pendências — exatamente o modo de falha que
         *     os filtros `pendenteRegistro`/`linkMeetStatus` existem para evitar. Os atalhos de
         *     período ("esta semana", "este mês") continuam como filtro, não como default.
         */
        get: operations["listarAgenda"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/profissional/agenda/resumo": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Contagens do painel da agenda, agregadas no servidor
         * @description As cinco métricas do topo de PF5, prontas. **Não aceita parâmetros**: os recortes
         *     de cada uma são fixos e definidos no servidor (ver a descrição de cada campo).
         *
         *     **Existe para o painel não ser montado com uma requisição por número.** Antes,
         *     a tela disparava quatro `GET /profissional/agenda` com `size=1` só para ler os
         *     totais do envelope, e uma quinta com `size=100` para somar a receita no cliente —
         *     a única parte da tela que supunha um volume máximo de sessões. Aqui a soma é do
         *     servidor, que é quem sabe o total de verdade.
         */
        get: operations["resumoAgenda"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/profissional/sessoes/grupo": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Cria uma sessão de grupo
         * @description PF4. Válido apenas para `RodaConversa` e `TerapiaGrupo`. A sessão nasce com
         *     `status: Agendada` e zero participantes, e fica visível na lista pública.
         *
         *     Limites de capacidade (D11, configuráveis): Roda de Conversa 3 a 12,
         *     Terapia em Grupo 3 a 8.
         *
         *     Exige valor definido para o tipo (PF3) — sem valor, a profissional não oferece
         *     aquele tipo e a criação é recusada com `VALOR_NAO_DEFINIDO`.
         */
        post: operations["criarSessaoGrupo"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sessoes/{sessaoId}/realizada": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Marca a sessão como realizada
         * @description PF6. Só é permitido após `dataHora` ter passado e a partir de
         *     `Agendada` ou `Confirmada`. `Realizada` é estado final e imutável.
         *
         *     Em sessões de grupo, marque a presença individual de cada participante
         *     (`PATCH /sessoes/{id}/participantes/{participanteId}`) **antes** desta chamada.
         */
        patch: operations["marcarSessaoRealizada"];
        trace?: never;
    };
    "/sessoes/{sessaoId}/nao-compareceu": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Marca a sessão como não comparecida
         * @description PF6. Aplicável a sessões individuais. Estado final e imutável.
         *     Incrementa o histórico de faltas da usuária, refletido em
         *     `noShowCount` e `exigePagamentoAntecipado` (D5).
         */
        patch: operations["marcarNaoCompareceu"];
        trace?: never;
    };
    "/sessoes/{sessaoId}/participantes/{participanteId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Marca a presença de um participante em sessão de grupo
         * @description PF6. Deve ser feito antes de marcar a sessão como realizada.
         */
        patch: operations["marcarPresencaParticipante"];
        trace?: never;
    };
    "/sessoes/{sessaoId}/link-meet": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Define manualmente o link da videochamada
         * @description D14. Caminho de contingência: se a criação automática do Meet falhar após as
         *     3 tentativas, a profissional é notificada e cola aqui um link gerado à mão.
         *     Disponibiliza o link para as participantes imediatamente.
         */
        patch: operations["definirLinkMeetManual"];
        trace?: never;
    };
    "/tipos-sessao": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Catálogo dos tipos de sessão
         * @description Metadados dos cinco tipos: duração, faixa de participantes, categoria e texto
         *     de apresentação.
         *
         *     **Existe para impedir que o frontend fixe regra de negócio em constante.**
         *     Sem este endpoint, a tela de escolha de tipo precisaria de um objeto com
         *     "Roda de Conversa, 60min, 3 a 12 pessoas" escrito no código — duplicando os
         *     limites que o backend usa para validar (D11) e criando duas fontes de verdade
         *     que divergem no dia em que a equipe Entre Ser confirmar outros números.
         *
         *     Resposta estável: pode ser cacheada pelo frontend por sessão do navegador.
         */
        get: operations["listarTiposSessao"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/profissionais": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Lista profissionais que oferecem um tipo de sessão
         * @description UF1. Retorna apenas profissionais ativas **e** com `ValorSessao` definido para
         *     o tipo solicitado. O campo `valor` já vem resolvido para o tipo consultado.
         */
        get: operations["listarProfissionais"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/profissionais/{profissionalId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Perfil público de uma profissional
         * @description Perfil completo com todos os tipos oferecidos e seus valores.
         *
         *     **Existe para sustentar deep link e recarga de página.** A listagem
         *     (`GET /profissionais`) devolve o resumo, mas a tela de perfil precisa
         *     funcionar quando a usuária chega por link direto ou aperta F5 — sem estado
         *     anterior em memória. Sem este endpoint, a tela quebraria no refresh e a
         *     solução improvisada seria refazer a listagem inteira e filtrar no cliente.
         */
        get: operations["detalharProfissional"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/profissionais/{profissionalId}/slots": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Lista os horários disponíveis de uma profissional
         * @description UF2. Executa o algoritmo de geração de slots (D1, D2, D3):
         *
         *     1. Busca a disponibilidade ativa do dia da semana
         *     2. Gera slots com passo `duracao + intervaloMinutos`, incluindo apenas os que
         *        couberem inteiros até `horaFim`
         *     3. Remove os que caem em `BloqueioAgenda`
         *     4. Remove os que se sobrepõem a sessões `Agendada`/`Confirmada`, considerando
         *        o intervalo como folga dos dois lados da sessão existente
         *     5. Remove os que começam em menos de 24h
         *
         *     A janela máxima consultável é de 90 dias.
         */
        get: operations["listarSlots"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sessoes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Marca uma sessão individual ou de casal
         * @description UF3 e UF4. Tipos aceitos: `Individual`, `Casal`, `Consultoria`.
         *     Para sessões de grupo use `POST /sessoes/{id}/inscrever`.
         *
         *     A sessão nasce em `status: Agendada`, com `linkMeet: null` — o link é gerado
         *     por job 30 minutos antes do início (D14). `valorPraticado` é um snapshot do
         *     valor da profissional no momento da marcação.
         *
         *     **Casal (D4):** informe `emailParceira`. Se o e-mail já pertence a uma usuária
         *     cadastrada, o `Participante` é criado direto e ela é notificada. Se não, é
         *     criado um `ConviteParticipante` e enviado o convite por e-mail. Em nenhum dos
         *     casos o convite bloqueia a sessão — ela é confirmada imediatamente.
         *
         *     **Concorrência:** a proteção contra dupla marcação é garantida por constraint
         *     de exclusão no banco, não por verificação na aplicação (D10).
         */
        post: operations["marcarSessao"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/grupos": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Lista as sessões de grupo abertas
         * @description UF5. Retorna apenas sessões com `dataHora` futura, `status: Agendada` e
         *     `vagasDisponiveis > 0`. O campo `vagasDisponiveis` já desconta as desistências
         *     (D7) — o frontend nunca calcula vagas.
         */
        get: operations["listarSessoesGrupo"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/grupos/{sessaoId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Detalha uma sessão de grupo aberta (pré-inscrição)
         * @description UF5. A tela que precede o botão "Inscrever-se", acessível a **qualquer usuária
         *     autenticada** — não exige ser participante. Retorna a forma pública
         *     `SessaoGrupoPublica`: sem lista de `participantes`, sem `linkMeet` e sem histórico
         *     de outras usuárias. O campo `jaInscrita` diz se a usuária autenticada já está
         *     inscrita, para a tela decidir o rótulo do botão sem uma segunda requisição.
         *
         *     Para o detalhe completo (já inscrita, ou a profissional), use `GET /sessoes/{sessaoId}`.
         */
        get: operations["detalharSessaoGrupo"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sessoes/{sessaoId}/inscrever": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Inscreve a usuária autenticada em uma sessão de grupo
         * @description UF5. Valida vagas, prazo (24h de antecedência) e inscrição duplicada.
         *     Se a usuária já esteve inscrita e desistiu, uma nova inscrição é permitida
         *     desde que haja vaga.
         */
        post: operations["inscreverEmGrupo"];
        /**
         * Desiste de uma sessão de grupo
         * @description UF5. Soft delete — preenche `saiuEm` no `Participante`, liberando a vaga.
         *     O registro permanece no histórico e continua visível para a profissional.
         *
         *     Permitido a qualquer momento. Com mais de 24h, sem cobrança; com menos de 24h,
         *     a resposta traz `cobrancaAplicada: true` (sem efeito financeiro no MVP). É a mesma
         *     regra do cancelamento de sessão individual — desistir tarde é permitido, cobrando
         *     o valor cheio.
         */
        delete: operations["sairDeGrupo"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/usuaria/sessoes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Lista as sessões da usuária autenticada
         * @description Inclui sessões individuais, de casal e inscrições em grupo.
         */
        get: operations["listarMinhasSessoes"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sessoes/{sessaoId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Detalha uma sessão
         * @description Detalhe completo (`Sessao`). Acessível apenas pela profissional dona da sessão
         *     e pelas participantes; para as demais, `403`.
         *
         *     **Sessão de grupo antes de inscrever:** quem ainda não é participante usa
         *     `GET /grupos/{sessaoId}`, que devolve a forma pública `SessaoGrupoPublica`
         *     (sem `participantes` nem `linkMeet`) com o campo `jaInscrita`.
         *
         *     **Visibilidade do link (D14):** `linkMeet` só é preenchido a partir de 30
         *     minutos antes do início. Antes disso vem `null`, e `linkMeetDisponivelEm`
         *     informa o instante em que passará a existir. O frontend nunca decide essa
         *     regra — apenas exibe o que recebe.
         *
         *     Campos `noShowCount` e `exigePagamentoAntecipado` das participantes são
         *     visíveis apenas para a profissional.
         */
        get: operations["detalharSessao"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sessoes/{sessaoId}/cancelar": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Cancela uma sessão
         * @description UF8 e PF7. Permitido para a usuária participante e para a profissional.
         *     `Cancelada` é estado final e imutável.
         *
         *     **Pela usuária:** com mais de 24h, sem cobrança. Com menos de 24h, a resposta
         *     traz `cobrancaAplicada: true` (sem efeito financeiro no MVP, pois o Módulo de
         *     Pagamento não está ativo). O frontend deve confirmar com a usuária antes de
         *     enviar quando `podeCancelarSemCobranca` for `false`.
         *
         *     **Pela profissional:** permitido a qualquer momento, sem penalidade.
         *
         *     Efeitos: notifica a outra parte, cancela o evento no Google Calendar se existir,
         *     e cancela convites pendentes.
         */
        post: operations["cancelarSessao"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sessoes/{sessaoId}/reagendar": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Reagenda uma sessão para outro horário
         * @description UF9. Mantém o mesmo registro de sessão (mesmo `id`, mesmos participantes) e
         *     altera apenas `dataHora`.
         *
         *     **Bloqueio dentro de 24h (D9):** não é possível reagendar uma sessão que começa
         *     em menos de 24h — nesse caso resta cancelar. O horário de destino também precisa
         *     respeitar as 24h de antecedência. Os dois lados são validados.
         *
         *     Efeitos colaterais obrigatórios: `linkMeet` volta a `null`, os lembretes já
         *     registrados são apagados para que os novos disparem, o evento antigo no Google
         *     Calendar é cancelado, e a profissional é notificada.
         *
         *     Não se aplica a sessões de grupo.
         */
        patch: operations["reagendarSessao"];
        trace?: never;
    };
    "/convites/{token}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Consulta um convite pelo token
         * @description D4. **Endpoint público** — não exige autenticação, pois a convidada pode ainda
         *     não ter conta. Alimenta a tela de aceite do convite.
         *
         *     O e-mail é devolvido mascarado para não expor o endereço a quem tenha o link.
         */
        get: operations["consultarConvite"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/convites/{token}/aceitar": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Aceita um convite de sessão de casal
         * @description D4. Exige autenticação — a convidada precisa ter se cadastrado antes.
         *     Cria o `Participante`, marca o convite como aceito e notifica quem convidou.
         *
         *     O e-mail da usuária autenticada precisa ser o mesmo do convite.
         */
        post: operations["aceitarConvite"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sessoes/{sessaoId}/convite": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Cancela o convite pendente de uma sessão de casal
         * @description D4. Permitido apenas para a usuária que criou a sessão.
         */
        delete: operations["cancelarConvite"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * @description Envelope único de erro. **O frontend exibe mensagem a partir de `code`**,
         *     através de um mapa `code → texto pt-BR`. O campo `message` é técnico,
         *     destinado a log, e nunca deve ser exibido nem comparado por texto.
         * @example {
         *       "code": "ANTECEDENCIA_MINIMA",
         *       "message": "Session must be booked at least 24 hours in advance",
         *       "details": {
         *         "minimoHoras": 24
         *       }
         *     }
         */
        Erro: {
            /**
             * @description Identificador estável do erro.
             * @example ANTECEDENCIA_MINIMA
             */
            code: string;
            /**
             * @description Descrição técnica em inglês, para log. Não exibir ao usuário.
             * @example Session must be booked at least 24 hours in advance
             */
            message: string;
            /**
             * @description Dados auxiliares específicos do erro.
             * @example {
             *       "minimoHoras": 24,
             *       "dataHoraSolicitada": "2026-08-12T14:00:00Z"
             *     }
             */
            details?: {
                [key: string]: unknown;
            };
        };
        /**
         * @description Tipo da sessão, que determina duração e número de participantes:
         *     `Individual` 50min / 1 · `Casal` 60min / 1-2 · `Consultoria` 60min / 1 ·
         *     `RodaConversa` 60min / 3-12 · `TerapiaGrupo` 90min / 3-8.
         * @example Individual
         * @enum {string}
         */
        TipoSessao: "Individual" | "Casal" | "Consultoria" | "RodaConversa" | "TerapiaGrupo";
        /**
         * @description Estados finais e imutáveis: `Realizada`, `Cancelada`, `NaoCompareceu`.
         *
         *     `Confirmada` existe no enum mas **não é atribuída no MVP** (D8): toda sessão
         *     nasce e permanece `Agendada` até um estado final. O frontend deve tratar
         *     `Agendada` e `Confirmada` como o mesmo estado visual.
         * @example Agendada
         * @enum {string}
         */
        StatusSessao: "Agendada" | "Confirmada" | "Realizada" | "Cancelada" | "NaoCompareceu";
        /**
         * @example Segunda
         * @enum {string}
         */
        DiaSemana: "Domingo" | "Segunda" | "Terca" | "Quarta" | "Quinta" | "Sexta" | "Sabado";
        /**
         * @description `Sistema` indica cancelamento automático de grupo sem quórum.
         * @example Usuaria
         * @enum {string}
         */
        CanceladoPor: "Usuaria" | "Profissional" | "Sistema";
        /**
         * @example Pendente
         * @enum {string}
         */
        StatusConvite: "Pendente" | "Aceito" | "Expirado" | "Cancelado";
        /**
         * @description Situação do link da videochamada (D14). Substitui um booleano simples porque
         *     a interface precisa distinguir três situações diferentes, e não duas:
         *
         *     - `Agendado` — ainda não chegou a janela de 30 minutos. Exibir a hora prevista.
         *     - `Disponivel` — link criado. Exibir o botão de entrar na sala.
         *     - `Falhou` — as 3 tentativas se esgotaram. **Exibir para a profissional a ação
         *       de colar um link manual** (`PATCH /sessoes/{id}/link-meet`).
         *     - `NaoAplicavel` — sessão cancelada ou já encerrada.
         *
         *     Sem o estado `Falhou`, a profissional não teria como localizar na agenda quais
         *     sessões precisam de ação, e a única saída seria uma rota nova só para listá-las.
         * @example Agendado
         * @enum {string}
         */
        LinkMeetStatus: "Agendado" | "Disponivel" | "Falhou" | "NaoAplicavel";
        /**
         * @description Hora local da profissional, formato `HH:mm` de 24 horas.
         * @example 09:00
         */
        Hora: string;
        Pagina: {
            /** @example 0 */
            page: number;
            /** @example 20 */
            size: number;
            /**
             * Format: int64
             * @example 137
             */
            totalElements: number;
            /** @example 7 */
            totalPages: number;
        };
        PaginaSessoes: components["schemas"]["Pagina"] & {
            content: components["schemas"]["SessaoResumo"][];
        };
        /**
         * @description Página de sessões da profissional, com as contagens de pendência do período
         *     inteiro. Os dois totais ignoram os filtros de pendência aplicados — assim o
         *     destaque continua mostrando "3 aguardando registro" mesmo enquanto a lista
         *     está filtrada por eles.
         */
        PaginaAgenda: components["schemas"]["Pagina"] & {
            content: components["schemas"]["SessaoResumo"][];
            /**
             * @description Sessões do período aguardando registro. Alimenta a contagem do destaque.
             * @example 3
             */
            totalPendenteRegistro: number;
            /**
             * @description Sessões do período com `linkMeetStatus = Falhou`.
             * @example 1
             */
            totalLinkMeetFalhou: number;
        };
        /**
         * @description As cinco contagens do topo da agenda (PF5), cada uma com o seu próprio recorte
         *     de tempo — por isso um objeto só, e não um número por requisição.
         */
        ResumoAgenda: {
            /**
             * @description Sessões ativas (`Agendada`/`Confirmada`) de hoje até +7 dias.
             * @example 6
             */
            proximos7Dias: number;
            /**
             * @description Sessões `Cancelada` nos últimos 14 dias.
             * @example 3
             */
            canceladas14Dias: number;
            /**
             * @description Sessões que já aconteceram e seguem sem registro. Mesma definição do
             *     `pendenteRegistro` do `SessaoResumo`, agregada.
             * @example 0
             */
            pendenteRegistro: number;
            /**
             * @description Sessões com `linkMeetStatus = Falhou`, aguardando link manual.
             * @example 0
             */
            linkMeetFalhou: number;
            /**
             * Format: double
             * @description Soma de `valorPraticado` das sessões agendadas e realizadas do mês corrente.
             *     Somado no servidor: no cliente, dependia de baixar uma página de até 100
             *     itens e supor que cabia tudo nela.
             * @example 830
             */
            receitaPrevistaMes: number;
        };
        PaginaProfissionais: components["schemas"]["Pagina"] & {
            content: components["schemas"]["ProfissionalResumo"][];
        };
        PaginaBloqueios: components["schemas"]["Pagina"] & {
            content: components["schemas"]["BloqueioAgenda"][];
        };
        FaixaDisponibilidade: {
            /** Format: uuid */
            id: string;
            diaSemana: components["schemas"]["DiaSemana"];
            horaInicio: components["schemas"]["Hora"];
            horaFim: components["schemas"]["Hora"];
            /**
             * @description Folga entre sessões consecutivas (D2). O passo de geração de slots é
             *     `duracao + intervaloMinutos`. Não editável na interface do MVP.
             * @default 10
             * @example 10
             */
            intervaloMinutos: number;
            /**
             * @description Permite desativar a faixa sem apagá-la.
             * @example true
             */
            ativa: boolean;
        };
        DisponibilidadeSemanal: {
            /**
             * @description Fuso da profissional, usado na geração de slots (D14). Fixo no MVP.
             * @example America/Sao_Paulo
             */
            timezone: string;
            faixas: components["schemas"]["FaixaDisponibilidade"][];
        };
        FaixaDisponibilidadeInput: {
            diaSemana: components["schemas"]["DiaSemana"];
            horaInicio: components["schemas"]["Hora"];
            horaFim: components["schemas"]["Hora"];
            /** @default 10 */
            intervaloMinutos: number;
            /** @default true */
            ativa: boolean;
        };
        /**
         * @example {
         *       "faixas": [
         *         {
         *           "diaSemana": "Segunda",
         *           "horaInicio": "09:00",
         *           "horaFim": "12:00",
         *           "intervaloMinutos": 10,
         *           "ativa": true
         *         },
         *         {
         *           "diaSemana": "Segunda",
         *           "horaInicio": "14:00",
         *           "horaFim": "18:00",
         *           "intervaloMinutos": 10,
         *           "ativa": true
         *         },
         *         {
         *           "diaSemana": "Terca",
         *           "horaInicio": "14:00",
         *           "horaFim": "18:00",
         *           "intervaloMinutos": 10,
         *           "ativa": true
         *         }
         *       ]
         *     }
         */
        DisponibilidadeSemanalInput: {
            /** @description Conjunto completo de faixas. Substitui o que existia. */
            faixas: components["schemas"]["FaixaDisponibilidadeInput"][];
        };
        DisponibilidadeAtualizadaResponse: {
            disponibilidade: components["schemas"]["DisponibilidadeSemanal"];
            /**
             * @description Sessões já marcadas que não cabem na nova disponibilidade. Não são
             *     canceladas — cabe à profissional decidir. Lista vazia é o caso comum.
             */
            sessoesForaDaNovaAgenda: components["schemas"]["SessaoResumo"][];
        };
        BloqueioAgenda: {
            /** Format: uuid */
            id: string;
            /**
             * Format: date-time
             * @example 2026-12-20T00:00:00Z
             */
            dataInicio: string;
            /**
             * Format: date-time
             * @example 2027-01-05T23:59:59Z
             */
            dataFim: string;
            /** Format: date-time */
            criadoEm: string;
        };
        BloqueioInput: {
            /**
             * Format: date-time
             * @example 2026-12-20T00:00:00Z
             */
            dataInicio: string;
            /**
             * Format: date-time
             * @example 2027-01-05T23:59:59Z
             */
            dataFim: string;
        };
        BloqueioCriadoResponse: {
            bloqueio: components["schemas"]["BloqueioAgenda"];
            /**
             * @description Sessões já marcadas dentro do período bloqueado. **Não são canceladas
             *     automaticamente.** O frontend deve listá-las e oferecer cancelamento
             *     individual.
             */
            sessoesAfetadas: components["schemas"]["SessaoResumo"][];
        };
        ValorSessao: {
            tipoSessao: components["schemas"]["TipoSessao"];
            /**
             * Format: double
             * @description Valor em reais **por participante** (D6). Numa Roda de Conversa com 8
             *     inscritas e valor 80,00, o bruto é R$ 640,00.
             *     `null` significa que a profissional não oferece esse tipo de sessão.
             * @example 250
             */
            valor: number | null;
            /** Format: date-time */
            atualizadoEm?: string | null;
        };
        ValoresSessaoResponse: {
            /** @description Sempre os cinco tipos. Os não oferecidos vêm com valor nulo. */
            valores: components["schemas"]["ValorSessao"][];
        };
        /**
         * @example {
         *       "valores": [
         *         {
         *           "tipoSessao": "Individual",
         *           "valor": 250
         *         },
         *         {
         *           "tipoSessao": "Casal",
         *           "valor": 350
         *         },
         *         {
         *           "tipoSessao": "Consultoria",
         *           "valor": 300
         *         },
         *         {
         *           "tipoSessao": "RodaConversa",
         *           "valor": 80
         *         },
         *         {
         *           "tipoSessao": "TerapiaGrupo",
         *           "valor": null
         *         }
         *       ]
         *     }
         */
        ValoresSessaoInput: {
            valores: {
                tipoSessao: components["schemas"]["TipoSessao"];
                /** Format: double */
                valor: number | null;
            }[];
        };
        ProfissionalResumo: {
            /** Format: uuid */
            id: string;
            /** @example Ana Souza */
            nome: string;
            /** Format: uri */
            foto?: string | null;
            /** @example 06/123456 */
            crp: string;
            /** @example Terapia Cognitivo-Comportamental */
            abordagem?: string | null;
            bio?: string | null;
            /**
             * Format: double
             * @description Valor para o tipo consultado em `GET /profissionais?tipo=`.
             * @example 250
             */
            valor?: number | null;
        };
        ProfissionalDetalhe: components["schemas"]["ProfissionalResumo"] & {
            /**
             * @description Apenas os tipos com valor definido. Já é a lista exata que a tela de
             *     perfil renderiza como opções de agendamento — o frontend não filtra nada.
             */
            tiposOferecidos: components["schemas"]["ValorSessao"][];
        };
        TipoSessaoInfo: {
            codigo: components["schemas"]["TipoSessao"];
            /** @example Roda de Conversa */
            nome: string;
            /**
             * @example 60
             * @enum {integer}
             */
            duracaoMinutos: 50 | 60 | 90;
            /** @example 3 */
            minParticipantes: number;
            /** @example 12 */
            maxParticipantes: number;
            /**
             * @description `Individual` — a usuária escolhe profissional e slot.
             *     `Grupo` — a profissional cria a sessão e as usuárias se inscrevem.
             *     Determina qual fluxo de marcação a interface apresenta.
             * @example Grupo
             * @enum {string}
             */
            categoria: "Individual" | "Grupo";
            /** @example Sessão em grupo com tema definido */
            descricao?: string;
        };
        /**
         * @example {
         *       "tipos": [
         *         {
         *           "codigo": "Individual",
         *           "nome": "Individual",
         *           "duracaoMinutos": 50,
         *           "minParticipantes": 1,
         *           "maxParticipantes": 1,
         *           "categoria": "Individual",
         *           "descricao": "Atendimento individual de psicologia"
         *         },
         *         {
         *           "codigo": "Casal",
         *           "nome": "Casal",
         *           "duracaoMinutos": 60,
         *           "minParticipantes": 1,
         *           "maxParticipantes": 2,
         *           "categoria": "Individual",
         *           "descricao": "Sessão para casal"
         *         },
         *         {
         *           "codigo": "Consultoria",
         *           "nome": "Consultoria por fase",
         *           "duracaoMinutos": 60,
         *           "minParticipantes": 1,
         *           "maxParticipantes": 1,
         *           "categoria": "Individual",
         *           "descricao": "Orientação sobre uma fase do ciclo"
         *         },
         *         {
         *           "codigo": "RodaConversa",
         *           "nome": "Roda de Conversa",
         *           "duracaoMinutos": 60,
         *           "minParticipantes": 3,
         *           "maxParticipantes": 12,
         *           "categoria": "Grupo",
         *           "descricao": "Sessão em grupo com tema definido"
         *         },
         *         {
         *           "codigo": "TerapiaGrupo",
         *           "nome": "Terapia em Grupo",
         *           "duracaoMinutos": 90,
         *           "minParticipantes": 3,
         *           "maxParticipantes": 8,
         *           "categoria": "Grupo",
         *           "descricao": "Terapia em grupo com acompanhamento contínuo"
         *         }
         *       ]
         *     }
         */
        TiposSessaoResponse: {
            tipos: components["schemas"]["TipoSessaoInfo"][];
        };
        Slot: {
            /**
             * Format: date-time
             * @example 2026-08-12T12:00:00Z
             */
            inicio: string;
            /**
             * Format: date-time
             * @example 2026-08-12T12:50:00Z
             */
            fim: string;
        };
        /**
         * @example {
         *       "profissionalId": "3f2a8c1e-9b4d-4e7a-8c1f-2d5e6a7b8c9d",
         *       "tipo": "Individual",
         *       "duracaoMinutos": 50,
         *       "valor": 250,
         *       "slots": [
         *         {
         *           "inicio": "2026-08-12T12:00:00Z",
         *           "fim": "2026-08-12T12:50:00Z"
         *         },
         *         {
         *           "inicio": "2026-08-12T13:00:00Z",
         *           "fim": "2026-08-12T13:50:00Z"
         *         },
         *         {
         *           "inicio": "2026-08-12T14:00:00Z",
         *           "fim": "2026-08-12T14:50:00Z"
         *         }
         *       ]
         *     }
         */
        SlotsResponse: {
            /** Format: uuid */
            profissionalId: string;
            tipo: components["schemas"]["TipoSessao"];
            /**
             * @example 50
             * @enum {integer}
             */
            duracaoMinutos: 50 | 60 | 90;
            /**
             * Format: double
             * @example 250
             */
            valor: number;
            /** @description Ordenados por `inicio`. Lista vazia é resposta válida. */
            slots: components["schemas"]["Slot"][];
        };
        UsuariaResumo: {
            /** Format: uuid */
            id: string;
            /** @example Marina Costa */
            nome: string;
            /** Format: uri */
            foto?: string | null;
            /**
             * @description Faltas sem aviso no histórico (D5). Campo derivado, calculado pelo backend.
             *     **Visível apenas para a profissional** — `null` nas demais respostas.
             * @example 0
             */
            noShowCount?: number | null;
            /**
             * @description `true` quando `noShowCount >= 1` (D5). Sem efeito financeiro no MVP, pois o
             *     Módulo de Pagamento não está ativo — serve como alerta para a profissional.
             *     **Visível apenas para a profissional.**
             * @example false
             */
            exigePagamentoAntecipado?: boolean | null;
        };
        Participante: {
            /** Format: uuid */
            id: string;
            usuaria: components["schemas"]["UsuariaResumo"];
            /** @description Marcado pela profissional após a sessão. `null` antes disso. */
            compareceu?: boolean | null;
            /** Format: date-time */
            inscritaEm: string;
            /**
             * Format: date-time
             * @description Preenchido na desistência (soft delete). Quem tem `saiuEm` não conta em
             *     `vagasDisponiveis`, mas permanece no histórico (D7).
             */
            saiuEm?: string | null;
        };
        /** @description Forma reduzida usada em listagens. */
        SessaoResumo: {
            /** Format: uuid */
            id: string;
            tipo: components["schemas"]["TipoSessao"];
            /**
             * Format: date-time
             * @example 2026-08-12T14:00:00Z
             */
            dataHora: string;
            /** @enum {integer} */
            duracaoMinutos: 50 | 60 | 90;
            status: components["schemas"]["StatusSessao"];
            profissional: components["schemas"]["ProfissionalResumo"];
            /** @example Ciclos e transições */
            tituloGrupo?: string | null;
            /** @description Capacidade máxima. Apenas em grupo. */
            vagas?: number | null;
            /**
             * @description Calculado pelo backend, já descontando desistências (D7).
             *     O frontend **nunca** deve calcular vagas a partir da lista de participantes.
             */
            vagasDisponiveis?: number | null;
            totalParticipantes?: number | null;
            /**
             * Format: double
             * @description Valor por participante.
             */
            valorPraticado?: number;
            linkMeetStatus?: components["schemas"]["LinkMeetStatus"];
            /**
             * @description `true` quando o horário já passou e a sessão continua ativa, aguardando o
             *     registro da profissional. Preenchido apenas em `GET /profissional/agenda`.
             *
             *     **Existe para o frontend não comparar datas.** Sem este campo, a tela
             *     precisaria de `dataHora < agora && status ∈ {Agendada, Confirmada}` — uma
             *     regra de negócio no componente, que erra em virada de fuso e some do lugar
             *     certo quando a regra mudar.
             * @example false
             */
            pendenteRegistro?: boolean | null;
            /**
             * @description Se a usuária autenticada já está inscrita nesta sessão de grupo.
             *     Preenchido apenas em `GET /grupos`; nulo nas demais listagens.
             *
             *     **Existe para decidir o rótulo do botão sem uma segunda requisição.**
             *     Sem este campo, a lista de grupos precisaria ser cruzada com
             *     `GET /usuaria/sessoes` no cliente para saber se o botão diz
             *     "Inscrever-se" ou "Você já está inscrita".
             * @example false
             */
            jaInscrita?: boolean | null;
            /**
             * @description Nome da participante da sessão individual ou de casal, para a agenda da
             *     profissional. Preenchido apenas em `GET /profissional/agenda`; nulo nas
             *     listagens da usuária (onde seria o próprio nome dela) e em sessões de grupo
             *     (que se identificam por `tituloGrupo`).
             *
             *     **Existe para a profissional ver de relance com quem é cada atendimento.**
             *     Sem este campo, `SessaoResumo` só traz `profissional` — no painel dela, o
             *     nome dela mesma — e a agenda cairia no nome do tipo ("Individual"), sem
             *     dizer quem. Espelha `pendenteRegistro`/`jaInscrita`: opcional, preenchido
             *     por contexto, nunca calculado no cliente.
             * @example Ana Souza
             */
            participanteNome?: string | null;
            /**
             * @description Quem cancelou, quando `status` é `Cancelada`; nulo nos demais status.
             *
             *     **Existe para a agenda separar cancelamento da usuária do da própria
             *     profissional.** A métrica "canceladas nos últimos 14 dias" quer dizer
             *     "desmarcaram comigo" — sem este campo ela somava também os cancelamentos
             *     que a profissional fez, atribuindo a ela mesma o que ela decidiu. Só existia
             *     em `Sessao` (o detalhe), e buscar o detalhe de cada item da listagem para
             *     contar seria N requisições por página.
             */
            canceladaPor?: components["schemas"]["CanceladoPor"] | null;
        };
        /**
         * @description Detalhe público de uma sessão de grupo aberta a inscrições — a tela que precede
         *     o botão "Inscrever-se", vista por qualquer usuária autenticada. Não traz
         *     `participantes`, `linkMeet` nem histórico de ninguém; só o necessário para decidir
         *     a inscrição.
         */
        SessaoGrupoPublica: {
            /** Format: uuid */
            id: string;
            tipo: components["schemas"]["TipoSessao"];
            /**
             * Format: date-time
             * @example 2026-08-20T18:00:00Z
             */
            dataHora: string;
            /**
             * @example 60
             * @enum {integer}
             */
            duracaoMinutos: 50 | 60 | 90;
            status: components["schemas"]["StatusSessao"];
            profissional: components["schemas"]["ProfissionalResumo"];
            /** @example Ciclos e transições */
            tituloGrupo: string;
            /** @description Capacidade máxima. */
            vagas: number;
            /** @description Calculado pelo backend, já descontando desistências (D7). */
            vagasDisponiveis: number;
            /**
             * Format: double
             * @description Valor por participante (D6).
             */
            valorPraticado: number;
            /**
             * @description Se a usuária autenticada já está inscrita nesta sessão. Existe para a tela
             *     decidir o rótulo do botão ("Inscrever-se" vs "Você já está inscrita" / "Sair")
             *     sem uma segunda requisição.
             * @example false
             */
            jaInscrita: boolean;
        };
        /** @description Forma completa, usada no detalhe e nas respostas de escrita. */
        Sessao: {
            /** Format: uuid */
            id: string;
            tipo: components["schemas"]["TipoSessao"];
            /**
             * Format: date-time
             * @example 2026-08-12T14:00:00Z
             */
            dataHora: string;
            /**
             * Format: date-time
             * @description Calculado como `dataHora + duracaoMinutos`. Evita duplicar a conta no frontend.
             * @example 2026-08-12T14:50:00Z
             */
            dataHoraFim: string;
            /**
             * @example 50
             * @enum {integer}
             */
            duracaoMinutos: 50 | 60 | 90;
            status: components["schemas"]["StatusSessao"];
            profissional: components["schemas"]["ProfissionalResumo"];
            participantes: components["schemas"]["Participante"][];
            /** @description Convite de casal ainda não aceito (D4). Nulo quando não há convite. */
            convitePendente?: components["schemas"]["ConviteResumo"] | null;
            /**
             * Format: uri
             * @description **Regra de visibilidade (D14):** `null` até 30 minutos antes do início.
             *     O backend controla essa janela; o frontend apenas exibe o que recebe e
             *     nunca esconde nem revela o link por conta própria.
             * @example null
             */
            linkMeet?: string | null;
            /**
             * Format: date-time
             * @description Instante a partir do qual `linkMeet` será preenchido (`dataHora - 30min`).
             * @example 2026-08-12T13:30:00Z
             */
            linkMeetDisponivelEm?: string | null;
            linkMeetStatus?: components["schemas"]["LinkMeetStatus"];
            vagas?: number | null;
            /** @description Calculado pelo backend (D7). */
            vagasDisponiveis?: number | null;
            tituloGrupo?: string | null;
            /**
             * Format: double
             * @description Snapshot do valor no momento do agendamento, **por participante** (D6).
             *     Não muda se a profissional alterar seus valores depois.
             * @example 250
             */
            valorPraticado: number;
            /**
             * @description Calculado pelo backend: `true` se faltam mais de 24h. O frontend usa para
             *     decidir se exibe o aviso de cobrança antes de confirmar — mas a decisão
             *     final é sempre do backend.
             * @example true
             */
            podeCancelarSemCobranca?: boolean;
            /**
             * @description `false` dentro das 24h ou em sessão de grupo (D9).
             * @example true
             */
            podeReagendar?: boolean;
            /**
             * @description `true` enquanto a sessão está em `Agendada` ou `Confirmada` — inclusive
             *     depois do horário, enquanto o registro não foi feito (PF7 permite o
             *     cancelamento pela profissional a qualquer momento).
             *
             *     Existe para a tela não decidir isso sozinha. A regra de quem pode cancelar
             *     e até quando difere entre usuária e profissional e tende a mudar; o
             *     componente só lê o booleano.
             * @example true
             */
            podeCancelar?: boolean;
            /**
             * @description `true` quando o horário já passou e a sessão continua ativa. É o que
             *     habilita a ação de registrar o que aconteceu, sem comparação de datas
             *     no frontend.
             * @example false
             */
            pendenteRegistro?: boolean;
            canceladaPor?: components["schemas"]["CanceladoPor"];
            /** Format: date-time */
            canceladaEm?: string | null;
            motivoCancelamento?: string | null;
            /** Format: date-time */
            criadaEm: string;
            /** Format: date-time */
            atualizadaEm: string;
        };
        /**
         * @example {
         *       "profissionalId": "3f2a8c1e-9b4d-4e7a-8c1f-2d5e6a7b8c9d",
         *       "tipo": "Individual",
         *       "dataHora": "2026-08-12T14:00:00Z"
         *     }
         */
        MarcarSessaoInput: {
            /** Format: uuid */
            profissionalId: string;
            tipo: components["schemas"]["TipoSessao"];
            /**
             * Format: date-time
             * @description Início escolhido, UTC. Precisa corresponder a um slot disponível.
             * @example 2026-08-12T14:00:00Z
             */
            dataHora: string;
            /**
             * Format: email
             * @description Apenas para `tipo: Casal` (D4). Se já cadastrada, vira participante direto.
             *     Se não, recebe um convite por e-mail. Em nenhum caso bloqueia a sessão.
             * @example parceira@exemplo.com
             */
            emailParceira?: string | null;
        };
        /**
         * @example {
         *       "tipo": "RodaConversa",
         *       "dataHora": "2026-08-20T18:00:00Z",
         *       "titulo": "Ciclos e transições",
         *       "vagas": 10
         *     }
         */
        SessaoGrupoInput: {
            /** @description Apenas `RodaConversa` ou `TerapiaGrupo`. */
            tipo: components["schemas"]["TipoSessao"];
            /**
             * Format: date-time
             * @example 2026-08-20T18:00:00Z
             */
            dataHora: string;
            /** @example Ciclos e transições */
            titulo: string;
            /**
             * @description Capacidade máxima. Limite por tipo (D11, configurável no backend):
             *     RodaConversa 3 a 12, TerapiaGrupo 3 a 8.
             * @example 10
             */
            vagas: number;
        };
        CancelamentoResponse: {
            sessao: components["schemas"]["Sessao"];
            /**
             * @description `true` quando o cancelamento ocorreu com menos de 24h de antecedência
             *     e foi feito pela usuária. Sem efeito financeiro enquanto o Módulo de
             *     Pagamento não estiver ativo — serve para a mensagem de confirmação.
             * @example false
             */
            cobrancaAplicada: boolean;
            /**
             * Format: double
             * @description Percentual do valor cobrado. `50` na regra atual.
             * @example null
             */
            percentualCobrado?: number | null;
        };
        ConviteResumo: {
            /** Format: uuid */
            id: string;
            /** @example p*****a@exemplo.com */
            emailMascarado: string;
            status: components["schemas"]["StatusConvite"];
            /**
             * Format: date-time
             * @description Igual a `sessao.dataHora` — não faz sentido aceitar depois da sessão.
             */
            expiraEm: string;
        };
        /**
         * @description Dados mínimos para a tela pública de aceite. Não expõe o e-mail completo
         *     nem dados da usuária que convidou.
         */
        ConvitePublico: {
            status: components["schemas"]["StatusConvite"];
            /** @example p*****a@exemplo.com */
            emailMascarado: string;
            /** Format: date-time */
            expiraEm: string;
            tipo: components["schemas"]["TipoSessao"];
            /** Format: date-time */
            dataHora: string;
            /** @example 60 */
            duracaoMinutos: number;
            profissional: components["schemas"]["ProfissionalResumo"];
            /** @example Marina */
            nomeQuemConvidou?: string;
        };
    };
    responses: {
        /** @description Requisição inválida */
        Erro400: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "code": "PARAMETRO_INVALIDO",
                 *       "message": "Invalid request parameter"
                 *     }
                 */
                "application/json": components["schemas"]["Erro"];
            };
        };
        /** @description `NAO_AUTENTICADO` — token ausente, inválido ou expirado. */
        Erro401: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "code": "NAO_AUTENTICADO",
                 *       "message": "Missing or invalid authentication token"
                 *     }
                 */
                "application/json": components["schemas"]["Erro"];
            };
        };
        /** @description `NAO_AUTORIZADO` — o recurso não pertence a quem está autenticado. */
        Erro403: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "code": "NAO_AUTORIZADO",
                 *       "message": "Resource does not belong to the authenticated principal"
                 *     }
                 */
                "application/json": components["schemas"]["Erro"];
            };
        };
        /** @description `RECURSO_NAO_ENCONTRADO` */
        Erro404: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "code": "RECURSO_NAO_ENCONTRADO",
                 *       "message": "Resource not found"
                 *     }
                 */
                "application/json": components["schemas"]["Erro"];
            };
        };
    };
    parameters: {
        SessaoId: string;
        ProfissionalId: string;
        BloqueioId: string;
        /** @description Token opaco do convite, gerado com SecureRandom. */
        Token: string;
        /** @description Página, começando em zero. */
        Page: number;
        Size: number;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    listarDisponibilidade: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Disponibilidade semanal */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DisponibilidadeSemanal"];
                };
            };
            401: components["responses"]["Erro401"];
            403: components["responses"]["Erro403"];
        };
    };
    definirDisponibilidade: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DisponibilidadeSemanalInput"];
            };
        };
        responses: {
            /** @description Disponibilidade atualizada */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DisponibilidadeAtualizadaResponse"];
                };
            };
            /**
             * @description Faixa inválida. Códigos possíveis: `FAIXA_INVALIDA` (horaFim <= horaInicio),
             *     `FAIXAS_SOBREPOSTAS` (duas faixas do mesmo dia se cruzam),
             *     `INTERVALO_INVALIDO` (intervaloMinutos negativo ou maior que 120).
             */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Erro"];
                };
            };
            401: components["responses"]["Erro401"];
            403: components["responses"]["Erro403"];
        };
    };
    listarBloqueios: {
        parameters: {
            query?: {
                incluirPassados?: boolean;
                /** @description Página, começando em zero. */
                page?: components["parameters"]["Page"];
                size?: components["parameters"]["Size"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Bloqueios */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginaBloqueios"];
                };
            };
            401: components["responses"]["Erro401"];
            403: components["responses"]["Erro403"];
        };
    };
    criarBloqueio: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BloqueioInput"];
            };
        };
        responses: {
            /** @description Bloqueio criado */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BloqueioCriadoResponse"];
                };
            };
            /** @description `PERIODO_INVALIDO` — dataFim anterior ou igual a dataInicio. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Erro"];
                };
            };
            401: components["responses"]["Erro401"];
            403: components["responses"]["Erro403"];
        };
    };
    removerBloqueio: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                bloqueioId: components["parameters"]["BloqueioId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Bloqueio removido */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Erro401"];
            403: components["responses"]["Erro403"];
            404: components["responses"]["Erro404"];
        };
    };
    listarValores: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Valores por tipo */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ValoresSessaoResponse"];
                };
            };
            401: components["responses"]["Erro401"];
            403: components["responses"]["Erro403"];
        };
    };
    definirValores: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ValoresSessaoInput"];
            };
        };
        responses: {
            /** @description Valores atualizados */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ValoresSessaoResponse"];
                };
            };
            /** @description `VALOR_INVALIDO` — valor negativo ou zero. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Erro"];
                };
            };
            401: components["responses"]["Erro401"];
            403: components["responses"]["Erro403"];
        };
    };
    listarAgenda: {
        parameters: {
            query: {
                /**
                 * @description Início do período (inclusivo), UTC.
                 * @example 2026-08-01T00:00:00Z
                 */
                de: string;
                /**
                 * @description Fim do período (exclusivo), UTC.
                 * @example 2026-08-31T23:59:59Z
                 */
                ate: string;
                /** @description Filtra por um ou mais status. Ausente, retorna todos. */
                status?: components["schemas"]["StatusSessao"][];
                tipo?: components["schemas"]["TipoSessao"][];
                /**
                 * @description `true` devolve apenas sessões cujo horário já passou e que continuam em
                 *     `Agendada`/`Confirmada` — as que aguardam o registro da profissional.
                 *
                 *     **Existe para o destaque de pendências da tela de agenda.** Filtrar no
                 *     cliente só alcançaria a página carregada: com 20 itens por página, uma
                 *     pendência na página 3 ficaria invisível, e "a profissional não vê que
                 *     precisa agir" é o pior modo de falha do painel.
                 */
                pendenteRegistro?: boolean;
                /**
                 * @description Filtra pela situação da sala. `Falhou` devolve as sessões que precisam de
                 *     link manual — a segunda pendência do painel. Mesmo motivo do parâmetro acima.
                 */
                linkMeetStatus?: components["schemas"]["LinkMeetStatus"][];
                /** @description Página, começando em zero. */
                page?: components["parameters"]["Page"];
                size?: components["parameters"]["Size"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /**
             * @description Sessões da profissional. O envelope traz `totalPendenteRegistro` e
             *     `totalLinkMeetFalhou` calculados sobre **todo o período consultado**, não
             *     sobre a página — é o que alimenta as contagens do destaque de pendências
             *     sem exigir uma segunda requisição.
             */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginaAgenda"];
                };
            };
            400: components["responses"]["Erro400"];
            401: components["responses"]["Erro401"];
            403: components["responses"]["Erro403"];
        };
    };
    resumoAgenda: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Contagens do período corrente. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResumoAgenda"];
                };
            };
            401: components["responses"]["Erro401"];
            403: components["responses"]["Erro403"];
        };
    };
    criarSessaoGrupo: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SessaoGrupoInput"];
            };
        };
        responses: {
            /** @description Sessão de grupo criada */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Sessao"];
                };
            };
            /**
             * @description Códigos possíveis: `TIPO_NAO_E_GRUPO`, `CAPACIDADE_INVALIDA`,
             *     `VALOR_NAO_DEFINIDO`, `ANTECEDENCIA_MINIMA`.
             */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Erro"];
                };
            };
            401: components["responses"]["Erro401"];
            403: components["responses"]["Erro403"];
            /** @description `CONFLITO_HORARIO` — a profissional já tem sessão nesse horário. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Erro"];
                };
            };
        };
    };
    marcarSessaoRealizada: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                sessaoId: components["parameters"]["SessaoId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Sessão marcada como realizada */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Sessao"];
                };
            };
            /**
             * @description Códigos possíveis: `SESSAO_NAO_OCORREU_AINDA` (dataHora no futuro),
             *     `TRANSICAO_INVALIDA` (sessão já está em estado final).
             */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Erro"];
                };
            };
            401: components["responses"]["Erro401"];
            403: components["responses"]["Erro403"];
            404: components["responses"]["Erro404"];
        };
    };
    marcarNaoCompareceu: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                sessaoId: components["parameters"]["SessaoId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Sessão marcada como não comparecida */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Sessao"];
                };
            };
            /** @description Códigos possíveis: `SESSAO_NAO_OCORREU_AINDA`, `TRANSICAO_INVALIDA`. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Erro"];
                };
            };
            401: components["responses"]["Erro401"];
            403: components["responses"]["Erro403"];
            404: components["responses"]["Erro404"];
        };
    };
    marcarPresencaParticipante: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                sessaoId: components["parameters"]["SessaoId"];
                participanteId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    compareceu: boolean;
                };
            };
        };
        responses: {
            /**
             * @description Presença registrada. Devolve a **sessão inteira atualizada**, não apenas o
             *     participante, para que a tela não precise de uma segunda requisição para
             *     se redesenhar.
             */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Sessao"];
                };
            };
            /** @description Códigos possíveis: `SESSAO_NAO_E_GRUPO`, `SESSAO_NAO_OCORREU_AINDA`. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Erro"];
                };
            };
            401: components["responses"]["Erro401"];
            403: components["responses"]["Erro403"];
            404: components["responses"]["Erro404"];
        };
    };
    definirLinkMeetManual: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                sessaoId: components["parameters"]["SessaoId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /**
                     * Format: uri
                     * @example https://meet.google.com/abc-defg-hij
                     */
                    linkMeet: string;
                };
            };
        };
        responses: {
            /** @description Link definido */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Sessao"];
                };
            };
            /** @description Códigos possíveis: `LINK_INVALIDO`, `TRANSICAO_INVALIDA`. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Erro"];
                };
            };
            401: components["responses"]["Erro401"];
            403: components["responses"]["Erro403"];
            404: components["responses"]["Erro404"];
        };
    };
    listarTiposSessao: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Catálogo de tipos */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TiposSessaoResponse"];
                };
            };
            401: components["responses"]["Erro401"];
        };
    };
    listarProfissionais: {
        parameters: {
            query: {
                tipo: components["schemas"]["TipoSessao"];
                /** @description Página, começando em zero. */
                page?: components["parameters"]["Page"];
                size?: components["parameters"]["Size"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Profissionais disponíveis */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginaProfissionais"];
                };
            };
            400: components["responses"]["Erro400"];
            401: components["responses"]["Erro401"];
        };
    };
    detalharProfissional: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                profissionalId: components["parameters"]["ProfissionalId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Perfil da profissional */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProfissionalDetalhe"];
                };
            };
            401: components["responses"]["Erro401"];
            404: components["responses"]["Erro404"];
        };
    };
    listarSlots: {
        parameters: {
            query: {
                /** @description Define a duração usada na geração (50, 60 ou 90 minutos). */
                tipo: components["schemas"]["TipoSessao"];
                /** @example 2026-08-01 */
                inicio: string;
                /** @example 2026-08-31 */
                fim: string;
            };
            header?: never;
            path: {
                profissionalId: components["parameters"]["ProfissionalId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /**
             * @description Slots disponíveis. Lista vazia é resposta válida (profissional sem
             *     disponibilidade, período todo bloqueado ou agenda cheia) — não é erro.
             */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SlotsResponse"];
                };
            };
            /**
             * @description Códigos possíveis: `PERIODO_INVALIDO`, `JANELA_MUITO_LONGA` (acima de 90 dias),
             *     `VALOR_NAO_DEFINIDO` (a profissional não oferece esse tipo).
             */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Erro"];
                };
            };
            401: components["responses"]["Erro401"];
            404: components["responses"]["Erro404"];
        };
    };
    marcarSessao: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MarcarSessaoInput"];
            };
        };
        responses: {
            /** @description Sessão criada */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Sessao"];
                };
            };
            /**
             * @description Códigos possíveis: `ANTECEDENCIA_MINIMA` (menos de 24h),
             *     `SLOT_INDISPONIVEL` (horário fora da disponibilidade ou em período bloqueado),
             *     `VALOR_NAO_DEFINIDO`, `TIPO_E_DE_GRUPO`, `EMAIL_PARCEIRA_INVALIDO`,
             *     `EMAIL_PARCEIRA_E_PROPRIO`.
             */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Erro"];
                };
            };
            401: components["responses"]["Erro401"];
            404: components["responses"]["Erro404"];
            /**
             * @description `SLOT_JA_OCUPADO` — outra usuária marcou esse horário primeiro.
             *     O frontend deve recarregar os slots e pedir nova escolha.
             */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "code": "SLOT_JA_OCUPADO",
                     *       "message": "Slot already booked by another user",
                     *       "details": {
                     *         "dataHora": "2026-08-12T14:00:00Z"
                     *       }
                     *     }
                     */
                    "application/json": components["schemas"]["Erro"];
                };
            };
        };
    };
    listarSessoesGrupo: {
        parameters: {
            query?: {
                /** @description Apenas `RodaConversa` ou `TerapiaGrupo`. */
                tipo?: components["schemas"]["TipoSessao"];
                profissionalId?: string;
                /** @description Página, começando em zero. */
                page?: components["parameters"]["Page"];
                size?: components["parameters"]["Size"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Sessões de grupo abertas */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginaSessoes"];
                };
            };
            400: components["responses"]["Erro400"];
            401: components["responses"]["Erro401"];
        };
    };
    detalharSessaoGrupo: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                sessaoId: components["parameters"]["SessaoId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Detalhe público da sessão de grupo */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessaoGrupoPublica"];
                };
            };
            /** @description `SESSAO_NAO_E_GRUPO` — o id não é de uma sessão de grupo. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Erro"];
                };
            };
            401: components["responses"]["Erro401"];
            404: components["responses"]["Erro404"];
        };
    };
    inscreverEmGrupo: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                sessaoId: components["parameters"]["SessaoId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Inscrição realizada */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Sessao"];
                };
            };
            /**
             * @description Códigos possíveis: `SESSAO_NAO_E_GRUPO`, `ANTECEDENCIA_MINIMA`,
             *     `TRANSICAO_INVALIDA` (sessão cancelada ou já realizada).
             */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Erro"];
                };
            };
            401: components["responses"]["Erro401"];
            404: components["responses"]["Erro404"];
            /** @description Códigos possíveis: `SESSAO_LOTADA`, `JA_INSCRITA`. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Erro"];
                };
            };
        };
    };
    sairDeGrupo: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                sessaoId: components["parameters"]["SessaoId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Desistência registrada */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CancelamentoResponse"];
                };
            };
            /** @description `NAO_INSCRITA` — a usuária não está inscrita nesta sessão. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Erro"];
                };
            };
            401: components["responses"]["Erro401"];
            404: components["responses"]["Erro404"];
        };
    };
    listarMinhasSessoes: {
        parameters: {
            query?: {
                status?: components["schemas"]["StatusSessao"][];
                de?: string;
                ate?: string;
                /** @description Página, começando em zero. */
                page?: components["parameters"]["Page"];
                size?: components["parameters"]["Size"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Sessões da usuária */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginaSessoes"];
                };
            };
            400: components["responses"]["Erro400"];
            401: components["responses"]["Erro401"];
        };
    };
    detalharSessao: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                sessaoId: components["parameters"]["SessaoId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Detalhe da sessão */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Sessao"];
                };
            };
            401: components["responses"]["Erro401"];
            403: components["responses"]["Erro403"];
            404: components["responses"]["Erro404"];
        };
    };
    cancelarSessao: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                sessaoId: components["parameters"]["SessaoId"];
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": {
                    /** @description Opcional. Exibido para a outra parte. */
                    motivo?: string;
                };
            };
        };
        responses: {
            /** @description Sessão cancelada */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CancelamentoResponse"];
                };
            };
            /** @description `TRANSICAO_INVALIDA` — a sessão já está em estado final. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Erro"];
                };
            };
            401: components["responses"]["Erro401"];
            403: components["responses"]["Erro403"];
            404: components["responses"]["Erro404"];
        };
    };
    reagendarSessao: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                sessaoId: components["parameters"]["SessaoId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /**
                     * Format: date-time
                     * @description Novo horário, UTC. Precisa ser um slot disponível.
                     * @example 2026-08-20T17:00:00Z
                     */
                    dataHora: string;
                };
            };
        };
        responses: {
            /** @description Sessão reagendada */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Sessao"];
                };
            };
            /**
             * @description Códigos possíveis: `PRAZO_REAGENDAMENTO` (sessão atual em menos de 24h),
             *     `ANTECEDENCIA_MINIMA` (novo horário em menos de 24h),
             *     `SLOT_INDISPONIVEL`, `SESSAO_E_DE_GRUPO`, `TRANSICAO_INVALIDA`.
             */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "code": "PRAZO_REAGENDAMENTO",
                     *       "message": "Session starts in less than 24h and cannot be rescheduled",
                     *       "details": {
                     *         "dataHoraAtual": "2026-07-28T10:00:00Z",
                     *         "horasRestantes": 6
                     *       }
                     *     }
                     */
                    "application/json": components["schemas"]["Erro"];
                };
            };
            401: components["responses"]["Erro401"];
            403: components["responses"]["Erro403"];
            404: components["responses"]["Erro404"];
            /** @description `SLOT_JA_OCUPADO` — o horário de destino foi ocupado. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Erro"];
                };
            };
        };
    };
    consultarConvite: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Token opaco do convite, gerado com SecureRandom. */
                token: components["parameters"]["Token"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Dados públicos do convite */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConvitePublico"];
                };
            };
            /** @description `CONVITE_INVALIDO` — token inexistente. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Erro"];
                };
            };
            /** @description `CONVITE_EXPIRADO` — a sessão já passou ou o convite foi cancelado. */
            410: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Erro"];
                };
            };
        };
    };
    aceitarConvite: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Token opaco do convite, gerado com SecureRandom. */
                token: components["parameters"]["Token"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Convite aceito, participante criada */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Sessao"];
                };
            };
            /**
             * @description Códigos possíveis: `CONVITE_JA_ACEITO`,
             *     `EMAIL_NAO_CONFERE` (o e-mail da conta é diferente do e-mail convidado).
             */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Erro"];
                };
            };
            401: components["responses"]["Erro401"];
            /** @description `CONVITE_INVALIDO` */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Erro"];
                };
            };
            /** @description `CONVITE_EXPIRADO` */
            410: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Erro"];
                };
            };
        };
    };
    cancelarConvite: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                sessaoId: components["parameters"]["SessaoId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Convite cancelado. Devolve a sessão atualizada, com `convitePendente` nulo. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Sessao"];
                };
            };
            401: components["responses"]["Erro401"];
            403: components["responses"]["Erro403"];
            /** @description `CONVITE_INVALIDO` — não há convite pendente nessa sessão. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Erro"];
                };
            };
        };
    };
}
